<?php
$uname1=$_REQUEST['uname'];
$pass1=$_REQUEST['pass'];
$name1=$_REQUEST['name'];
$add1=$_REQUEST['add'];
$coun1=$_REQUEST['country'];
$code1=$_REQUEST['code'];
$mail1=$_REQUEST['mail'];
$m1=$_REQUEST['m'];
$e1=$_REQUEST['e'];
$about1=$_REQUEST['about'];
echo "<table border=1>
<tr>
<td>username</td>
<td>$uname1</td>
</tr>
<tr>
<td>password</td>
<td>$pass1</td>
</tr>
<tr>
<td>name</td>
<td>$name1</td>
</tr>
<tr>
<td>address</td>
<td>$add1</td>
</tr>
<tr>
<td>country</td>
<td>$coun1</td>
</tr>
<tr>
<td>ZIP code</td>
<td>$code1</td>
</tr>
<tr>
<td>email</td>
<td>$mail1</td>
</tr>
<tr>
<td>sex</td>
<td>$m1</td>
</tr>
<tr>
<td>language</td>
<td>$e1</td></tr>
<tr>
<td>about</td>
<td>$about1</td>
</tr></table>"

?>